#!/bin/bash

set -ex

## Generate ledger-cli reports
# Requires at least ledger 3
# Other prerequisites
#	gnuplot and the gnuplot scripts from this repo
#	piechart (https://github.com/cbdevnet/piechart)
#	A matching ledgerrc (see this repo)

# Run as ./report <ledger file>
# Resulting graphs will be placed in the reports/ directory
# The script uses the following categories
#	Assets
#	Expenses
#	Liabilities
#	Income
#	Expenses:Food

# Assume ledger file if none given
export LEDGER_FILE=${1:-"main.ledger"}

# Get current date and ledger command
DATE=$(date +%Y%m%d)
LEDGER="ledger --init-file ./ledgerrc"

plot(){
# The gnuplot scripts accept the following parameters
#	SVGTITLE	Title of the SVG document
#	TITLE		Title of the image
#	LEGEND		Chart legend text

	printf "%s" "$1" | xargs $LEDGER | $2
}

line(){
	plot "$1" "./single.gnuplot"
}

bar(){
	plot "$1" "./single-bar.gnuplot"
}

SVGTITLE="WeeklyAssets"	TITLE="Assets, weekly"	LEGEND="Assets" \
	line "--total-data --weekly --collapse --market register Assets" > reports/$DATE-Assets-Weekly.svg
SVGTITLE="Assets" 	TITLE="Assets, all TX"	LEGEND="Assets" \
	line "--total-data --collapse --market register Assets" > reports/$DATE-Assets.svg
SVGTITLE="Equity" 	TITLE="Equity, all TX"	LEGEND="Liquid Assets vs Liabilities" \
	line "--total-data --collapse register Assets:Liquid Liabilities" > reports/$DATE-Equity.svg

SVGTITLE="Balance"	TITLE="Monthly Balance"	LEGEND="Expenses (Positive implies overspending)" \
	bar "--amount-data --collapse --monthly register ^Income ^Expenses" > reports/$DATE-Balance-Monthly.svg

SVGTITLE="Food"		TITLE="Food Expenses"	LEGEND="Expenses:Food" \
	bar "--amount-data --collapse --monthly register ^Expenses:Food" > reports/$DATE-Food-Monthly.svg

SVGTITLE="Expenses"	TITLE="Monthly Expenses" LEGEND="Expenses" \
	line "--amount-data --collapse --monthly register Expenses" > reports/$DATE-Expenses-Monthly.svg

$LEDGER --depth 2 --balance-format "%T|%A\n" balance Expenses | tail -n +2 | head -n -1 | piechart --delimiter "|" --order value,legend --color random > reports/$DATE-Expense-Pie.svg
$LEDGER --depth 2 --balance-format "%T|%A\n" balance Assets | tail -n +2 | head -n -1 | piechart --delimiter "|" --order value,legend --color random > reports/$DATE-AssetsOverview-Pie.svg
